import React from "react";
import { format, isValid } from "date-fns";
import { parseAndValidateDate } from "@/utils/dateUtils";
import { useProfile } from "@/context/ProfileContext";

interface AiSummaryPdfContentProps {
  reportTitle: string;
  summaryText: string;
  reportDate: string;
}

const AiSummaryPdfContent: React.FC<AiSummaryPdfContentProps> = ({
  reportTitle,
  summaryText,
  reportDate,
}) => {
  const { profile } = useProfile();

  if (!profile || !profile.companyProfile) {
    return <div className="text-center text-red-500">Error: Company profile not loaded.</div>;
  }

  const reportDateObj = parseAndValidateDate(reportDate);

  return (
    <div className="bg-white text-gray-900 font-sans text-sm p-[20mm]">
      <div className="flex justify-between items-start mb-8">
        <div>
          {profile.companyProfile.companyLogoUrl ? (
            <img src={profile.companyProfile.companyLogoUrl} alt="Company Logo" className="max-h-20 object-contain mb-2" style={{ maxWidth: '1.5in' }} />
          ) : (
            <div className="max-h-20 mb-2" style={{ maxWidth: '1.5in' }}></div>
          )}
          <h1 className="text-5xl font-extrabold uppercase tracking-tight mb-2">
            AI REPORT SUMMARY
          </h1>
          <p className="text-lg font-semibold text-gray-700">For: {reportTitle ?? "N/A"}</p>
        </div>
        <div className="text-right">
          <p className="text-sm font-semibold">SUMMARY DATE: {reportDateObj && isValid(reportDateObj) ? format(reportDateObj, "MMM dd, yyyy HH:mm") : "N/A"}</p>
        </div>
      </div>

      <div className="mb-8">
        <p className="font-bold mb-2">REPORT FOR:</p>
        <div className="bg-gray-50 p-3 border border-gray-200 rounded">
          <p className="font-semibold">{profile.companyProfile.companyName || "Your Company"}</p>
          <p>{profile.companyProfile.companyCurrency || "N/A"}</p>
          <p>{(profile.companyProfile.companyAddress?.split('\n')[0] || "N/A")}</p>
          <p>{(profile.companyProfile.companyAddress?.split('\n')[1] || "")}</p>
        </div>
      </div>

      <div className="mb-8">
        <p className="font-bold mb-2">SUMMARY:</p>
        <div className="bg-gray-50 p-3 border border-gray-200 rounded min-h-[150px]">
          <p className="whitespace-pre-wrap">{summaryText ?? "No summary available."}</p>
        </div>
      </div>

      <div className="text-xs text-gray-500 mt-12 text-right">
        <p>Generated by Fortress AI on {reportDateObj && isValid(reportDateObj) ? format(reportDateObj, "MMM dd, yyyy HH:mm") : "N/A"}</p>
      </div>
    </div>
  );
};

export default AiSummaryPdfContent;